/**
 * @Author: PDK
 * @Date:   2018-09-04
 * @Last modified by:   PDK
 * @Last modified time: 2018-09-04
 */
export const REQUEST_MOVIE_LIST = 'REQUEST_MOVIE_LIST'
export const RECEIVE_MOVIE_LIST = 'RECEIVE_MOVIE_LIST'
export const TIGGER_SAVE_CURRENT_MOVIE = 'TIGGER_SAVE_CURRENT_MOVIE'
export const REQUEST_CINEMA_LIST = 'REQUEST_CINEMA_LIST'
export const RECEIVE_CINEMA_LIST = 'RECEIVE_CINEMA_LIST'
export const TIGGER_SAVE_CURRENT_CINEMA = 'TIGGER_SAVE_CURRENT_CINEMA'
