/**
 * @Author: PDK
 * @Date:   2018-09-05
 * @Last modified by:   PDK
 * @Last modified time: 2018-09-05
 */
export const RECEIVE_USER_INFORMATION = 'RECEIVE_USER_INFORMATION'
export const TIGGER_SAVE_CURRENT_MOVIE = 'TIGGER_SAVE_CURRENT_MOVIE'
export const REQUEST_USER_INFOMATION = 'REQUEST_USER_INFOMATION'
export const RECEIVE_GET_USER_INFO = 'RECEIVE_GET_USER_INFO'